
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wulin_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: zf4121789
    security:
      debug: false
logging:
  level:
    controller: debug
    org.springframework.web: debug
    org.springframework.jdbc: debug
    com.alibaba.druid: debug
---
cors:
  allow-origin: '*'
