
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wulinacademy?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: user
      password: user&user
logging:
  level:
    ROOT: debug
    controller: debug
    org:
      springframework:
        security: debug
        web: error
        jdbc: debug
    com.alibaba.druid: debug

---
cors:
  allow-origin: '*'
