
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wulin_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
logging:
  level:
    controller: debug
    org.springframework.web: debug
    org.springframework.jdbc: debug
    com.alibaba.druid: debug
  pattern:
    controller:
      console:
---
cors:
  allow-origin: '*'
