
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/wulin_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
    security:
      debug: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 700
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
logging:
  level:
    ROOT: info
    controller: debug
    org:
      springframework:
        security: debug
        web: error
        jdbc: debug
    com.alibaba.druid: debug

---
cors:
  allow-origin: '*'
