
spring:
  datasource:
    druid:
      url: jdbc:mysql://wulinacademy:39002/wulin_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: wulin-dev
      password: 'Xj%zG@mkf0@VsYEt'
    security:
      debug: false
logging:
  level:
    ROOT: info
    controller: debug
    org:
      springframework:
        security: debug
        web: error
        jdbc: debug
    com.alibaba.druid: debug

---
cors:
  allow-origin: '*'
