security:
  csrf:
    token:
      inHeaderName: auth-token
      inParamName: _authToken
      stranger: 'stranger'
  login:
    usernameOfParamName: username
    passwordOfParamName: password
  user:
    username: login
    password: login