security:
  csrf:
    token:
      inHeaderName: auth-token
      inParamName: _authToken
      stranger: 'stranger'
  login:
    usernameOfParamName: username
    passwordOfParamName: password
---
login-users:
  users:
    - username: login
      password: login
      status: 1
    - username: test
      password: test
      status: 0
---
folder:
  root-id: 0